### ISSUE TITLE
DEMO!

### ISSUE THREAD

**Issue by ghost** [Mr-Un1k0d3r/MaliciousMacroGenerator#2]
hello ,first thanks for this project, can you putt small demo please

**Comment by Mr-Un1k0d3r** [comment]
Which kind of demo you'd like to see? a video of the whole process?

**Comment by ghost** [comment]
yes , if you have time..thanks in advance

2017-01-10 20:45 GMT+01:00 Mr-Un1k0d3r <notifications@github.com>:
